# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Regexp-NamedCaptures
version:      0.01
version_from: lib/Regexp/NamedCaptures.pm
installdirs:  site
requires:
    Carp:                          0
    strict:                        0
    Text::Balanced:                0
    warnings:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
