--- #YAML:1.0
name: Regexp-NamedCaptures
version: 0.03
author:
  - "Joshua ben Jore" <jjore@cpan.org>
abstract: Saves capture results to your own variables
license: perl
generated_by: Module::Build version 0.2611, without YAML.pm
